# Generated by Django 3.0.5 on 2020-04-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата записи')),
                ('cpu', models.FloatField(verbose_name='Утилизация CPU в %')),
            ],
            options={
                'verbose_name': 'Основную информацию',
                'verbose_name_plural': 'Основная информация',
            },
        ),
    ]
