# Generated by Django 3.0.5 on 2020-04-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpudata',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата записи'),
        ),
    ]
